name: Nasa project CI
on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      MONGO_URL: mongodb://localhost/nasa
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        mongo-version: ['4.4']
    steps:
      - uses: actions/checkout@v2

      - name: Use Nodejs version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Start MongoDB"
        uses: supercharge/mongodb-github-action@1.9.0
        with:
          mongodb-version: ${{ matrix.mongo-version }}

      - run: npm install
      - run: npm run build --prefix client
      - run: npm test

  # deploy:
  #   needs: build
    